mcu: #micro controller unit
  alias: Arduino 2560 Mega
  component_name: arduino # Name of component to use in HAL
  dev: COM8 # Used for initial programming
  debug: true #optional
  enabled: True
  connection:
    ## A user can optionally define this section. If they don't, the config defaults to Serial, 115200 baud
    type: Serial
    baudrate: 115200                 #optional
    #connection_serial2: 0                       #optional - not sure what you get with a second serial port
    timeout: 5000 #optional, defaults to 5000 ms
    ## UDP Example
    #type: UDP #required for UDP
    #arduino_ip: 192.168.1.22 #required for UDP
    #arduino_port: 54321 # optional, default is 54321
    #listen_port: 54321 # optional, default is set to arduino_port  
    #timeout: 5000 #optional, defaults to 5000 ms

  io_map:
    analogInputs:
      - pin_id: 0
        pin_name: ain #hal pin name           #optional
        pin_smoothing: 200 #smoothing const   #optional
        pin_min_val: 10 #minimum value         #optional     these could be used to convert the value to 0-10 for example
        pin_max_val: 4096 #maximum value      #optional
      - pin_id: 1
        pin_name: test #hal pin name           #optional
      - pin_id: 3
        pin_name: anain #hal pin name           #optional
      - pin_id: 4
      - pin_id: 5
        pin_smoothing: 500 #smoothing const   #optional
      - pin_id: 6
        pin_min_val: 100 #minimum value         #optional     these could be used to convert the value to 0-10 for example
      - pin_id: 7
        pin_max_val: 2048 #maximum value      #optional
      - pin_id: 8
        pin_name: aaaabbbb #hal pin name           #optional
        pin_smoothing: 600 #smoothing const   #optional
        pin_min_val: 1000 #minimum value         #optional     these could be used to convert the value to 0-10 for example
        pin_max_val: 4096 #maximum value      #optional
    
