mcu: 
  alias: Arduino R4 Wifi
  component_name: arduino # Name of component to use in HAL
  dev: /dev/cu.usbmodem11101 # Used for initial programming
  #dev: /dev/cu.usbmodemF412FA68D6802 
  
  io_map:
        
    digitalInputs:
      - pin_id: 3
        pin_name: din.3 #hal pin name
        input_pullup: true
      - pin_id: 4
        pin_name: din.4 #hal pin name
        input_pullup: true
      - pin_id: 5
        pin_name: din.5 #hal pin name
        input_pullup: true        
      - pin_id: 6
        pin_name: din.6 #hal pin name
      - pin_id: 7
        pin_name: din.7 #hal pin name
      - pin_id: 8
        pin_name: din.8 #hal pin name
      - pin_id: 9
        pin_name: din.9 #hal pin name
      - pin_id: 10
        pin_name: din.10 #hal pin name
      - pin_id: 11
        pin_name: din.11 #hal pin name
      - pin_id: 12
        pin_name: din.12 #hal pin name
      - pin_id: 14
        pin_name: din.14 #hal pin name
      - pin_id: 15
        pin_name: din.15 #hal pin name
      - pin_id: 16
        pin_name: din.16 #hal pin name
      - pin_id: 17
        pin_name: din.17 #hal pin name
    digitalOutputs:
      - pin_id: 51
        pin_name: dout.51
      - pin_id: 13
        pin_name: dout.13 #hal pin name
        