mcu: 
  alias: Arduino R4 Wifi
  component_name: arduino # Name of component to use in HAL
  #dev: /dev/cu.usbmodem14201  # Used for initial programming
  dev: /dev/cu.usbmodemF412FA68D6802 
  #dev: /dev/cu.usbserial-0001
  io_map:
        
    digitalInputs:
      - pin_id: 3
        pin_name: din.3 #hal pin name
        input_pullup: true
        pin_debounce: 0
      - pin_id: 4
        pin_name: din.4 #hal pin name
        input_pullup: true
      - pin_id: 5
        pin_name: din.5 #hal pin name
        input_pullup: true        
      - pin_id: 6
        pin_name: din.6 #hal pin name
        input_pullup: true     
      - pin_id: 7
        pin_name: din.7 #hal pin name
        input_pullup: true     
      - pin_id: 8
        pin_name: din.8 #hal pin name
        input_pullup: true     
      - pin_id: 9
        pin_name: din.9 #hal pin name
        input_pullup: true     
      - pin_id: 10
        pin_name: din.9 #hal pin name
        input_pullup: true    

    digitalOutputs:
      - pin_id: 51
        pin_name: dout.51
      - pin_id: 13
        pin_name: dout.13 #hal pin name
        