mcu: 
  alias: Arduino R4 Wifi
  component_name: arduino # Name of component to use in HAL
  dev: /dev/cu.usbmodemF412FA68D6802 # Used for initial programming
  
  io_map:

    analogInputs:
      - pin_id: 0
        pin_name: ain.0 #hal pin name
        pin_type: HAL_FLOAT #hal pin type
        
    analogOutputs:
      - pin_id: 1
        pin_name: aout.1 #hal pin name
        pin_type: HAL_FLOAT #hal pin type
        
    digitalInputs:
      - pin_id: 3
        pin_name: din.3 #hal pin name
        pin_type: HAL_BIT #hal pin type
      - pin_id: 4
        pin_name: din.4 #hal pin name
      - pin_id: 5
        pin_name: din.5 #hal pin name        
      - pin_id: 6
        pin_name: din.6 #hal pin name
      - pin_id: 7
        pin_name: din.7 #hal pin name
      - pin_id: 8
        pin_name: din.8 #hal pin name

    digitalOutputs:
      - pin_id: 9
        pin_name: dout.9 #hal pin name
        
      - pin_id: 10
        pin_name: dout.10 #hal pin name
