//This file is generated automaticly by arduino-connector.py at :2024-12-20 11:18:43
//Do not edit this file to keep it in sync
//This Configuration has the ID 3888105603, it is used to detect Firmware Versions
#define FIRMWAREID 3888105603

//IO Settings of mcu no 0
//Alias :Arduino 2560 Mega

//Connection Settings
#define CONNECTION_TYPE serial
#define CONNECTION_BAUDRATE 115200
#define CONNECTION_TIMEOUT 5000

//I/O Settings
 
//Analog Inputs
#define AINPUTS
#define ANALOG_INPUTS 8

    const int AInPinmap[] = {0,1,3,4,5,6,7,8};
    const int AInPinSmoothing[] = {200,200,200,200,500,200,200,600};
    const int allIntInPinsAdresses[] = {0,1,2,3,4,5,6,7};
// Communication Setup
#define allBitInPins 0
#define allIntInPins 8
#define allFloatInPins 0
#define allBitOutPins 0
#define allIntOutPins 0
#define allFloatOutPins 0
#define numInPins 8
#define numOutPins 0
