//This file is generated automaticly by arduino-connector.py at :2024-11-24 03:03:44
//Do not edit this file to keep it in sync
//This Configuration has the ID 1732413824, it is used to detect Firmware Versions
#define FIRMWAREID 1732413824

//IO Settings of mcu no 0
//Alias :Arduino 2560 Mega

//Connection Settings
#define CONNECTION_TYPE serial
#define CONNECTION_BAUDRATE 115200
#define CONNECTION_TIMEOUT 5000

//I/O Settings
 
//Analog Inputs
#define AINPUTS
#define ANALOG_INPUTS 8
    const int AInPinmap[] = {0,1,3,4,5,6,7,8};
    const int AInPinSmoothing[] = {200,200,200,200,500,200,200,600};
    const int AInPinAdresses[] = {0,1,2,3,4,5,6,7};

//Digital Inputs
#define INPUTS
#define DigitalInputs 1
    const int InPinmap[] = {4};
    const int InPinModes[] = {0};
    const int InPinDebounce[] = {1};
    const int InPinPullups[] = {1};
    const int InPinAdresses[] = {0};

//Digital Outputs
#define OUTPUTS
#define DigitalOutputs 2
    const int OutPinmap[] = {8,12};
    const int OutPinInit[] = {1,1};
    const int OutPinDisconnect[] = {0,0};
    const int OutPinConnect[] = {0,0};
    const int OutPinAdresses[] = {0,1};

//latching Poti
#define LPOTI
#define LinearPotis 2
    const int LPotiPinmap[] = {1,2};
    const int LPotiPinLatches[] = {0,0};
    const int LPotiPinMargins[] = {20,20};
    const int LPotiPinAdresses[] = {1,2};

//Binary Selector Switch
#define BINSEL
#define BinarySelectorSwitches 1
    const int BSSPinmap[] = {2,6,4,3,5};
    const int BSSPinAdresses[] = {8,9,10,11,12};

//Joystick
#define JOYSTICK
#define Joysticks 1
    const int JSPinmap[] = {2};
    const int JSCenter[] = {512};
    const int JSDeadband[] = {20};
    const float JSScaling[] = {0.01};
    const int JSPinAdresses[] = {8};

//Status LED
#define STATUSLED
    const int StatusLed = 13;
    int StatLedErrDel[] = {1000,10};   //Blink Timing for Status LED Error (no connection)
    const int UseDLedStatusLed = 1;

#define DIGITALLEDS
    const int DLedPin = 6;
    const int DledBrightness = 70;
    const int DLedInits[18] = {0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1};
    const int DLedPinModes[18] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
    const int DLedPin_on_values[18][3] = {{0, 0, 0},{0, 255, 0},{255, 10, 10},{0, 0, 0},{0, 0, 0},{0, 0, 0},{0, 0, 0},{0, 0, 0},{0, 0, 0},{0, 0, 0},{0, 0, 0},{0, 0, 0},{0, 0, 0},{0, 0, 0},{0, 0, 0},{255, 255, 255},{0, 0, 255},{1, 2, 3}};
    const int DLedPin_off_values[18][3] = {{0, 0, 0},{0, 0, 0},{90, 80, 70},{0, 0, 0},{0, 0, 0},{0, 0, 0},{0, 0, 0},{0, 0, 0},{0, 0, 0},{0, 0, 0},{0, 0, 0},{0, 0, 0},{0, 0, 0},{0, 0, 0},{0, 0, 0},{0, 0, 0},{0, 0, 0},{0, 0, 0}};
    const int DLedPin_Fades[18] = {0,10,10,0,0,0,0,0,0,0,0,0,0,0,0,10,10,10};
    const int DLedAdresses[18] = {2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19};
    const int DLedChainLength = 200;

