//This file is generated automaticly by arduino-connector.py at :2024-12-25 16:55:40
//Do not edit this file to keep it in sync
//This Configuration has the ID 2630164023, it is used to detect Firmware Versions
#define FIRMWAREID 2630164023

//IO Settings of mcu no 0
//Alias :Arduino 2560 Mega

//Connection Settings
#define CONNECTION_TYPE serial
#define CONNECTION_BAUDRATE 115200
#define CONNECTION_TIMEOUT 5000

//I/O Settings
 
//Analog Inputs
#define AINPUTS
#define ANALOG_INPUTS 8

    const int AInPinmap[] = {0,1,3,4,5,6,7,8};
    const int AInPinSmoothing[] = {200,200,200,200,500,200,200,600};
    const int InInt16Pins[] = {0,1,2,3,4,5,6,7};

// Communication Variables
 //These variables are used to store the data that is sent and received over the serial interface.
#define InBinaryLength 0
bool InBinaryValues [1] = {0};
#define InInt16Length 8
 int InInt16Values [8] = {0};
#define InUint16Length 0
 unsigned int InUint16Values [1] = {0};
#define InInt32Length 0
 long InInt32Values [1] = {0};
#define InUint32Length 0
 unsigned long InUint32Values [1] = {0};
#define InFloatLength 0
 float InFloatValues [1] = {0.0};
#define InCharLength 0
 char InCharValues [1] = {""};
#define InStringLength 0
 char InStringValues [1] = {""};

#define OutBinaryLength 87
bool OutBinaryValues [87] = {0};
#define OutInt16Length 0
 int OutInt16Values [1] = {0};
#define OutUint16Length 0
 unsigned int OutUint16Values [1] = {0};
#define OutInt32Length 0
 long OutInt32Values [1] = {0};
#define OutUint32Length 0
 unsigned long OutUint32Values [1] = {0};
#define OutFloatLength 0
 float OutFloatValues [1] = {0.0};
#define OutCharLength 0
 char OutCharValues [1] = {""};
#define OutStringLength 0
 char OutStringValues [1] = {""};

