//This file is generated automaticly by arduino-connector.py at :2024-11-10 04:29:37
//Do not edit this file to keep it in sync

//IO Settings of mcu no 0

//Analog Inputs
#define AINPUTS
#define ANALOG_INPUTS 8
    const int AInPinmap[] = {0,1,3,4,5,6,7,8};
    const int AInPinSmoothing[] = {200,200,200,200,500,200,200,600};

//PWM Outputs
#define PWMOUTPUTS
#define PwmOutputs 1
    const int PWMPinmap[] = {12};
    const int PWMPinInit[] = {0};

//Digital Inputs
#define DINPUTS
#define DigitalInputs 1
    const int DInPinmap[] = {4};
    const int DInPinModes[] = {0};
    const int DInPinDebounce[] = {1};
    const int DInPinPullups[] = {1};

//Digital Outputs
#define DOUTPUTS
#define DigitalOutputs 1
    const int DOutPinmap[] = {8};
    const int DOutPinInit[] = {1};
    const int DOutPinDisconnect[] = {-1};
    const int DOutPinConnect[] = {-1};

//Linear Poti
#define LPOTI
#define LinearPotis 2
    const int LPotiPinmap[] = {1,2};
    const int LPotiPinLatches[] = {0,0};
    const int LPotiPinMargins[] = {20,20};

//Binary Selector Switch
#define BINSEL
#define BinarySelectorSwitches 1
    const int BSSPinmap[] = {0};
    const int BSSPinPins[][5] = {{2,6,4,3,5}};

//Quadrature Encoder
#define QUADENC
#define QuadratureEncoders 1
    const int QEPinmap[] = {0};
    const int QEPinModes[] = {0};
    const int QEPinPins[] = {0};
    const int QEPinSteps[] = {4};

//Joystick
#define JOYSTICK
#define Joysticks 1
    const int JSPinmap[] = {2};
    const int JSCenter[] = {512};
    const int JSDeadbands[] = {20};
    const float JSScaling[] = {0.01};

//Status LED
#define STATUSLED
    const int StatusLed = 13;
      const int StatLedErrDel[] = {1000,10};   //Blink Timing for Status LED Error (no connection)
    const int DLEDSTATUSLED = 1;

//Digital LED
#define DIGITALLEDS
    const int DLedPin = 4;
    const int DLedCount = 5;
    const int DLedPinInit[] = {0};
    const int DLedPinModes[] = {0};
    const int DLedPin_on_values[] = {255};
    const int DLedPin_off_values[] = {0};
    const int DLedPin_Fade = 0;

