//This file is generated automaticly by arduino-connector.py at :2024-12-26 10:03:44
//Do not edit this file to keep it in sync
//This Configuration has the ID 2630164023, it is used to detect Firmware Versions
#define FIRMWAREID 2630164023

//IO Settings of mcu no 0
//Alias :Arduino 2560 Mega

//Connection Settings
#define CONNECTION_TYPE serial
#define CONNECTION_BAUDRATE 115200
#define CONNECTION_TIMEOUT 5000

//I/O Settings
 
//Analog Inputs
#define AINPUTS
#define ANALOG_INPUTS 8

    const int AInPinmap[] = {0,1,3,4,5,6,7,8};
    const int AInPinSmoothing[] = {200,200,200,200,500,200,200,600};
    const int InInt16Pins[] = {0,1,2,3,4,5,6,7};

// Communication Variables
 //These variables are used to store the data that is sent and received over the serial interface.
#define InBinaryLength 87
bool InBinaryValues [87] = {0};
#define InInt16Length 2
 int InInt16Values [2] = {0};
#define InUint16Length 2
 unsigned int InUint16Values [2] = {0};
#define InInt32Length 2
 long InInt32Values [2] = {0};
#define InUint32Length 0
 unsigned long InUint32Values [2] = {0};
#define InFloatLength 2
 float InFloatValues [2] = {0.0};
#define InCharLength 2
 char InCharValues [2] = {""};
#define InStringLength 0
 char InStringValues [2] = {""};

#define OutBinaryLength 89
bool OutBinaryValues [89] = {0};
#define OutInt16Length 2
 int OutInt16Values [2] = {0};
#define OutUint16Length 2
 unsigned int OutUint16Values [2] = {0};
#define OutInt32Length 2
 long OutInt32Values [2] = {0};
#define OutUint32Length 2
 unsigned long OutUint32Values [2] = {0};
#define OutFloatLength 2
 float OutFloatValues [2] = {0.0};
#define OutCharLength 2
 char OutCharValues [2] = {""};
#define OutStringLength 3
 char* OutStringValues [3] = {""};

