//This file is generated automaticly by arduino-connector.py at :2024-12-20 11:18:43
//Do not edit this file to keep it in sync
//This Configuration has the ID 3432648373, it is used to detect Firmware Versions
#define FIRMWAREID 3432648373

//IO Settings of mcu no 1
//Alias :Esp8826

//Connection Settings
#define CONNECTION_TYPE serial
#define CONNECTION_BAUDRATE 115200
#define CONNECTION_TIMEOUT 5000

//I/O Settings
 
// Communication Setup
#define allBitInPins 0
#define allIntInPins 0
#define allFloatInPins 0
#define allBitOutPins 0
#define allIntOutPins 0
#define allFloatOutPins 0
#define numInPins 0
#define numOutPins 0
