import yaml, time, threading, os, serial, struct

from queue import Queue

def load_config(file_path):
    with open(file_path, 'r') as file:
        configs = list(yaml.safe_load_all(file))
    return configs
debug = True


def process_config(configs, writeFirmwareConfig=False):
    file_handle = None
    for i,config in enumerate(configs):
        if config['mcu'].get('enabled', True) == True:
            if(writeFirmwareConfig):
                file_handle = open(f'firmware{i}.h', 'w')
                current_time = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime())

                file_handle.write(f"//This file is generated automaticly by arduino-connector.py at :{current_time}\n")
                file_handle.write("//Do not edit this file to keep it in sync\n")
                firmwareID = compute_hash(config)
                file_handle.write(f"//This Configuration has the ID {firmwareID}, it is used to detect Firmware Versions\n")
                file_handle.write(f"#define FIRMWAREID {firmwareID}\n")
                file_handle.write("\n")
                # Write the unix_timestamp back into the config
                #config['mcu']['firmware_ID'] = unix_timestamp


            mcu = config.get('mcu', {})
            alias = mcu.get('alias', f'MCU-{i}')

            component_name = mcu.setdefault('component_name', 'arducon')
            dev = mcu.setdefault('dev', 'Unknown')
            debug = mcu.setdefault('debug', False)
            enabled = mcu.setdefault('enabled', True)
            connection_type = mcu.setdefault('connection_type', 'serial')
            connection_baudrate = mcu.setdefault('connection_baudrate', 115200)
            connection_timeout = mcu.setdefault('connection_timeout', 5000)

            if(writeFirmwareConfig):
                file_handle.write(f'//IO Settings of mcu no {i}\n//Alias :{alias}\n')
                file_handle.write("\n")
                file_handle.write(f'//Connection Settings\n')
                file_handle.write(f'#define CONNECTION_TYPE {connection_type}\n')
                file_handle.write(f'#define CONNECTION_BAUDRATE {connection_baudrate}\n')
                file_handle.write(f'#define CONNECTION_TIMEOUT {connection_timeout}\n\n')
                file_handle.write(f'//I/O Settings\n \n')

            if debug == True:
                
                print(f"MCU Alias: {alias}")
                print(f"Component Name: {component_name}")
                print(f"Device: {dev}")
                print(f"Enabled: {enabled}")
                print(f"Connection Type: {connection_type}")
                print(f"Connection Baudrate: {connection_baudrate}")
                print("IO Map:")

            io_map = mcu.get('io_map', {})

            
            analog_inputs = io_map.get('analogInputs', [])
            pwm_outputs = io_map.get('pwmOutputs', [])
            digital_inputs = io_map.get('digitalInputs', [])
            digital_outputs = io_map.get('digitalOutputs', [])
            lPoti = io_map.get('lPoti', [])
            binarySelectorSwitch = io_map.get('binarySelectorSwitch', [])
            quadratureEncoder = io_map.get('quadratureEncoder', [])
            joystick = io_map.get('joystick', [])
            statusled = io_map.get('statusled', [])
            digitalLed = io_map.get('digitalLed', [])
            matrixKeyboard = io_map.get('matrixKeyboard', [])
            LEDmultiplexing = io_map.get('LEDmultiplexing', [])
            dallasThermistor = io_map.get('dallasThermistor', [])
            rcServo = io_map.get('rcServo', [])
            Stepper = io_map.get('Stepper', [])

            #create an arrays with all Pin Types for communication and state storage
            InBinaryPins = []
            InInt16Pins = []
            InUint16Pins = []
            InInt32Pins = []
            InUint32Pins = []
            InFloatPins = []
            InCharPins = []
            InStringPins = []

            OutBinaryPins = []
            OutInt16Pins = []
            OutUint16Pins = []
            OutInt32Pins = []
            OutUint32Pins = []
            OutFloatPins = []
            OutCharPins = []
            OutStringPins = []
            



            ### Analog Inputs  #done
            if analog_inputs:
                AInputs = 0
                for pin in analog_inputs:
                    if pin.get('pin_enabled', True):
                        AInputs += 1

                if AInputs > 0:
                    if debug == True:
                        print("Analog Inputs:")

                    if writeFirmwareConfig == True:
                        file_handle.write(f'//Analog Inputs\n')
                        file_handle.write(f'#define AINPUTS\n')
                        file_handle.write(f'#define ANALOG_INPUTS {AInputs}\n\n')
                    
                    AInPinmap = []
                    AInPinSmoothings = []
                    AInAdresses = []

                    AInPins = {}
                    for i, pin in enumerate(analog_inputs):
                        if pin.get('pin_enabled', True):
                            pin_id = pin.get('pin_id', pin)

                            AInPinmap.append(pin.get('pin_id', pin))
                            AInPinSmoothings.append(pin.get('pin_smoothing', 200))
                            address = InInt16Pins[-1]['InInt16Pins'] + 1 if InInt16Pins else 0
                            AInPins[pin_id] = {
                                'pin_name': pin.get('pin_name', f"ain-{i}"),
                                'pin_smoothing': pin.get('pin_smoothing', 200),
                                'pin_min_val': pin.get('pin_min_val', 0),
                                'pin_max_val': pin.get('pin_max_val', 255),
                                'InInt16Pins': address
                            }
                            AInAdresses.append(address)
                            InInt16Pins.append(AInPins[pin_id])

                        
                    if debug == True:
                        print(InInt16Pins[-1])
                    
                    if writeFirmwareConfig == True:
                        file_handle.write(f'    const int AInPinmap[] = {{{",".join(map(str, AInPinmap))}}};\n')
                        file_handle.write(f'    const int AInPinSmoothing[] = {{{",".join(map(str, AInPinSmoothings))}}};\n')
                        file_handle.write(f'    const int InInt16Pins[] = {{{",".join(map(str, AInAdresses))}}};\n')


            ### PWM Outputs
            if pwm_outputs:
                PwmOutputs = 0
                for pin in pwm_outputs:
                    if pin.get('pin_enabled', True):
                        PwmOutputs += 1

                if PwmOutputs > 0:
                    if debug == True:
                        print("PWM Outputs:")
                        
                    if writeFirmwareConfig == True:
                        file_handle.write(f'//PWM Outputs\n')
                        file_handle.write(f'#define PWMOUTPUTS\n')
                        file_handle.write(f'#define PwmOutputs {PwmOutputs}\n')
                    
                    PwmOutPinmap = []
                    PWMPinNames = []
                    PWMPinInit = []
                    PWMPinModes = []
                    PWMPin_on_values = []
                    PWMPin_off_values = []

                    

                    for pin in pwm_outputs:
                        if pin.get('pin_enabled', True):
                            PwmOutPinmap.append(pin.get('pin_id', pin))
                            PWMPinNames.append(pin.get('pin_name', f"pwm-{pin}"))
                            PWMPinInit.append(pin.get('pin_init_state', 0))
                            PWMPinModes.append(pin.get('pin_mode', 0))
                            PWMPin_on_values.append(pin.get('pin_on_value', 255))
                            PWMPin_off_values.append(pin.get('pin_off_value', 0))

                            if debug == True:
                                print(PwmOutPinmap[-1])
                                print(PWMPinNames[-1])
                                print(PWMPinInit[-1])
                                print(PWMPinModes[-1])
                                print(PWMPin_on_values[-1])
                                print(PWMPin_off_values[-1])
                            
                    if writeFirmwareConfig == True:
                        file_handle.write(f'    const int PwmOutPinmap[] = {{{",".join(map(str, PwmOutPinmap))}}};\n')
                        file_handle.write(f'    const int PWMPinInit[] = {{{",".join(map(str, PWMPinInit))}}};\n')
                        file_handle.write(f'\n')

            ### Digital Inputs  #done
            if digital_inputs:
                Inputs = 0	
                for pin in digital_inputs:
                    if pin.get('pin_enabled', True):
                        Inputs += 1
                
                if Inputs > 0:
                    if debug == True:
                        print("Digital Inputs:")
                    if writeFirmwareConfig == True:
                        file_handle.write(f'//Digital Inputs\n')
                        file_handle.write(f'#define INPUTS\n')
                        file_handle.write(f'#define DigitalInputs {Inputs}\n')
                
                    InPinmap = []
                    InPinModes = []
                    InPinDebounce = []
                    InPinPullups = []
                    InPinAdresses = []

                    dInPins = {}
                    for i, pin in enumerate(digital_inputs):
                        if pin.get('pin_enabled', True):
                            pin_id = pin.get('pin_id', pin)

                            InPinmap.append(pin.get('pin_id', pin))
                            InPinModes.append(pin.get('pin_mode', 0))
                            InPinDebounce.append(pin.get('pin_debounce', 20))
                            InPinPullups.append(pin.get('pin_pullup', 1))
                            
                            address = allBitInPins[-1]['allBitInPinsAdresses'] + 1 if allBitInPins else 0
                            dInPins[pin_id] = {
                                'pin_name': pin.get('pin_name', f"din-{i}"),
                                'pin_mode': pin.get('pin_mode', 0),
                                'pin_debounce': pin.get('pin_debounce', 20),
                                'pin_pullup': pin.get('pin_pullup', 1),
                                'pin_inverted': pin.get('pin_inverted', 0),
                                'allBitInPinsAdresses': address
                            }
                            InPinAdresses.append(address)
                            allBitInPins.append(dInPins[pin_id])
                    if debug == True:
                        print(allBitInPins[-1])
                
                            
                    if writeFirmwareConfig == True:
                        file_handle.write(f'    const int InPinmap[] = {{{",".join(map(str, InPinmap))}}};\n')
                        file_handle.write(f'    const int InPinModes[] = {{{",".join(map(str, InPinModes))}}};\n')
                        file_handle.write(f'    const int InPinDebounce[] = {{{",".join(map(str, InPinDebounce))}}};\n')
                        file_handle.write(f'    const int InPinPullups[] = {{{",".join(map(str, InPinPullups))}}};\n')
                        addresses = [pin['allBitInPinsAdresses'] for pin in allBitInPins]
                        file_handle.write(f'    const int InPinAdresses[] = {{{",".join(map(str, addresses))}}};\n')
                        #file_handle.write(f'    const int InPinAdresses[] = {{{",".join(map(str, allBitInPins['allBitInPinsAdresses']))}}};\n')
                        file_handle.write(f'\n')
                
            ### Digital Outputs
            if digital_outputs:
                Outputs = 0
                for pin in digital_outputs:
                    if pin.get('pin_enabled', True):
                        Outputs += 1
                
                if Outputs > 0:
                    if debug == True:
                        print("Digital Outputs:")
                    if writeFirmwareConfig == True:
                        file_handle.write(f'//Digital Outputs\n')
                        file_handle.write(f'#define OUTPUTS\n')
                        file_handle.write(f'#define DigitalOutputs {Outputs}\n')
                
                    OutPinmap = []
                    OutPinNames = []
                    OutPinTypes = []
                    OutPinInit = []
                    OutPinDisconnected_states = []
                    OutPinConnected_states = []



                    for pin in digital_outputs:
                        if pin.get('pin_enabled', True):
                            OutPinmap.append(pin.get('pin_id', pin))
                            OutPinNames.append(pin.get('pin_name', f"out-{pin}"))
                            OutPinInit.append(pin.get('pin_init_state', 0))
                            OutPinTypes.append(pin.get('pin_type', 0))
                            OutPinDisconnected_states.append(pin.get('pin_on_disconnected', 0))
                            OutPinConnected_states.append(pin.get('pin_on_connected', 0))           
                            allBitOutPins.append(allBitOutPins[-1] + 1 if allBitOutPins else 0)
                            
                        if debug == True:
                            print(OutPinmap[-1])
                            print(OutPinNames[-1])
                            print(OutPinTypes[-1])
                            print(OutPinInit[-1])
                            print(OutPinDisconnected_states[-1])
                            print(OutPinConnected_states[-1])
                            print(allBitOutPins[-1])   
                            
                    if writeFirmwareConfig == True:
                        file_handle.write(f'    const int OutPinmap[] = {{{",".join(map(str, OutPinmap))}}};\n')
                        file_handle.write(f'    const int OutPinInit[] = {{{",".join(map(str, OutPinInit))}}};\n')
                        file_handle.write(f'    const int OutPinDisconnect[] = {{{",".join(map(str, OutPinDisconnected_states))}}};\n')
                        file_handle.write(f'    const int OutPinConnect[] = {{{",".join(map(str, OutPinConnected_states))}}};\n')
                        file_handle.write(f'    const int OutPinAdresses[] = {{{",".join(map(str, allBitOutPins[-Outputs:]))}}};\n')
                        file_handle.write(f'\n')

            ### Potentiometer
            if lPoti:
                LPotis = 0
                for pin in lPoti:
                    if pin.get('pin_enabled', True):
                        LPotis += 1
                
                if LPotis > 0:
                    if debug == True:
                        print("Latching Potentiometer:")
                    if writeFirmwareConfig == True:
                        file_handle.write(f'//latching Poti\n')
                        file_handle.write(f'#define LPOTI\n')
                        file_handle.write(f'#define LinearPotis {LPotis}\n')
                
                    LPotiPinmap = []
                    LPotiPinNames = []
                    LPotiPinLatches = []
                    LPotiPinTypes = []
                    LPotiPinValues = []
                    LPotiPinMargins = []
                    LPotiPinModes = []




                    for pin in lPoti:
                        if pin.get('pin_enabled', True):
                            LPotiPinmap.append(pin.get('pin_id', pin))
                            LPotiPinNames.append(pin.get('pin_name', f"lpoti-{pin}"))
                            LPotiPinLatches.append(pin.get('pin_latch', 0))	
                            LPotiPinTypes.append(pin.get('pin_type', 0))
                            LPotiPinValues.append(pin.get('value_replace', 0))
                            LPotiPinMargins.append(pin.get('pin_margin', 20))
                            LPotiPinModes.append(pin.get('pin_mode', 0))
                            allBitInPins.append(allBitInPins[-1] + 1 if allBitInPins else 0)

                        
                            if debug == True:
                                print(LPotiPinmap[-1])
                                print(LPotiPinNames[-1])
                                print(LPotiPinLatches[-1])
                                print(LPotiPinTypes[-1])
                                print(LPotiPinValues[-1])
                                print(LPotiPinMargins[-1])
                                print(LPotiPinModes[-1])
                                print(allBitInPins[-1])
                            
                    if writeFirmwareConfig == True:
                        file_handle.write(f'    const int LPotiPinmap[] = {{{",".join(map(str, LPotiPinmap))}}};\n')
                        file_handle.write(f'    const int LPotiPinLatches[] = {{{",".join(map(str, LPotiPinLatches))}}};\n')
                        file_handle.write(f'    const int LPotiPinMargins[] = {{{",".join(map(str, LPotiPinMargins))}}};\n')
                        file_handle.write(f'    const int LPotiPinAdresses[] = {{{",".join(map(str, allBitInPins[-LPotis:]))}}};\n')
                        
                        file_handle.write(f'\n')

            ### Binary Selector Switch
            if binarySelectorSwitch:
                BSS = 0
                for pin in binarySelectorSwitch:
                    if pin.get('pin_enabled', True):
                        BSS += 1
                
                if BSS > 0:
                    if debug == True:
                        print("Binary Selector Switch:")
                    if writeFirmwareConfig == True:
                        file_handle.write(f'//Binary Selector Switch\n')
                        file_handle.write(f'#define BINSEL\n')
                        file_handle.write(f'#define BinarySelectorSwitches {BSS}\n')
                
                    BSSPinmap = []
                    #BSSPinNames = []
                    BSSPinPins = []
                    BSSPinTypes = []
                    #BSSPinValues = []

                    BSSPinAdresses = []
                    BSSPins = {}
                    for i, pin in enumerate(binarySelectorSwitch):
                        if pin.get('pin_enabled', True):
                            BSSPinmap.append(pin.get('pin_id', pin))
                            BSSPinNames.append(pin.get('pin_name', f"bss-{pin}"))
                            BSSPinPins.extend(pin.get('pin_pins', []))
                            BSSPinTypes.append(pin.get('pin_type', 0))
                            #BSSPinValues.append(pin.get('pin_value', 0))
                            for _ in range(len(BSSPinPins)):
                                allBitInPins.append(allBitInPins[-1] + 1 if allBitInPins else 0)
                            if debug == True:
                                print(BSSPinmap[-1])
                                #print(BSSPinNames[-1])
                                print(BSSPinPins[0])
                                print(BSSPinTypes[-1])
                                #print(BSSPinValues[-1])
                                print(allBitInPins[-1])


                    for pin in binarySelectorSwitch:
                        if pin.get('pin_enabled', True):
                            BSSPinmap.append(pin.get('pin_id', pin))
                            BSSPinNames.append(pin.get('pin_name', f"bss-{pin}"))
                            BSSPinPins.extend(pin.get('pin_pins', []))
                            BSSPinTypes.append(pin.get('pin_type', 0))
                            BSSPinValues.append(pin.get('pin_value', 0))
                            for _ in range(len(BSSPinPins)):
                                allBitInPins.append(allBitInPins[-1] + 1 if allBitInPins else 0)
                            if debug == True:
                                print(BSSPinmap[-1])
                                print(BSSPinNames[-1])
                                print(BSSPinPins[0])
                                print(BSSPinTypes[-1])
                                print(BSSPinValues[-1])
                                print(allBitInPins[-1])
                            
                    if writeFirmwareConfig == True:
                        file_handle.write('    const int BSSPinmap[] = {')
                        for i in range(len(BSSPinPins)):
                            file_handle.write(f'{BSSPinPins[i]}')
                            if i < len(BSSPinPins) - 1:
                                file_handle.write(',')
                        file_handle.write('};\n')
                        file_handle.write('    const int BSSPinAdresses[] = {')
                        for i in range(len(BSSPinPins)):
                            allBitInPins.append(allBitInPins[-1] + 1 if allBitInPins else 0)
                            file_handle.write(f'{allBitInPins[-1]}')
                            if i < len(BSSPinPins) - 1:
                                file_handle.write(',')
                        file_handle.write('};\n')
                    
                        
                        file_handle.write(f'\n')


            ### Quadrature Encoder
            if quadratureEncoder:
                
                QE = 0
                for pin in quadratureEncoder:
                    if pin.get('pin_enabled', True):
                        QE += 1

                if QE > 0:
                    if debug == True:
                        print("Quadrature Encoder:")
                    if writeFirmwareConfig == True:
                        file_handle.write(f'//Quadrature Encoder\n')
                        file_handle.write(f'#define QUADENC\n')
                        file_handle.write(f'#define QuadratureEncoders {QE}\n')
                
                    QEPinmap = []
                    QEPinNames = []
                    QEPinModes = []
                    QEPinPins = []
                    QEPin_steps = []
                    QEPinvirtualpins = []
                    QEPinVirtualStartPins = []
                    QEPinTypes = []
                    QEPinValues = []



                    for pin in quadratureEncoder:
                        if pin.get('pin_enabled', True):
                            QEPinmap.append(pin.get('pin_id', pin))
                            QEPinNames.append(pin.get('pin_name', f"quadEnc.{pin}"))
                            QEPinModes.append(pin.get('pin_mode', 0))
                            QEPinPins.append(pin.get('pin_pins', 0))
                            QEPin_steps.append(pin.get('pin_steps', 4))
                            QEPinvirtualpins.append(pin.get('pin_virtualpins', 0))
                            QEPinVirtualStartPins.append(pin.get('pin_virtualstartpins', 0))
                            QEPinTypes.append(pin.get('pin_type', 0))
                            QEPinValues.append(pin.get('pin_value', 0))

                    if writeFirmwareConfig == True:
                        file_handle.write(f'    const int QEPinmap[] = {{{",".join(map(str, QEPinmap))}}};\n')
                        file_handle.write(f'    const int QEPinModes[] = {{{",".join(map(str, QEPinModes))}}};\n')
                        file_handle.write(f'    const int QEPinPins[] = {{{",".join(map(str, QEPinPins))}}};\n')
                        file_handle.write(f'    const int QEPinSteps[] = {{{",".join(map(str, QEPin_steps))}}};\n')
                        file_handle.write(f'\n')

            ### Joystick
            if joystick:
                JS = 0
                for pin in joystick:
                    if pin.get('pin_enabled', True):
                        JS += 1

                if JS > 0:
                    
                    if debug == True:
                        print("Joystick:")
                    if writeFirmwareConfig == True:
                        file_handle.write(f'//Joystick\n')
                        file_handle.write(f'#define JOYSTICK\n')
                        file_handle.write(f'#define Joysticks {JS}\n')
                
                    JSPinmap = []
                    JSPinNames = []
                    JSPinCenter = []
                    JSPinDeadbands = []
                    JSPinScaling = []
                        

                    for pin in joystick:
                        if pin.get('pin_enabled', True):
                            JSPinmap.append(pin.get('pin_id', pin))
                            JSPinNames.append(pin.get('pin_name', f"joystick-{pin}"))
                            JSPinCenter.append(pin.get('pin_center', 512))
                            JSPinDeadbands.append(pin.get('pin_deadband', 20))
                            JSPinScaling.append(pin.get('pin_scaling', 0.01))
                            allIntInPins.append(allIntInPins[-1] + 1 if allIntInPins else 0)

                            if debug == True:
                                print(JSPinmap[-1])
                                print(JSPinNames[-1])
                                print(JSPinCenter[-1])
                                print(JSPinDeadbands[-1])
                                print(JSPinScaling[-1])
                                print(allIntInPins[-1])

                        if writeFirmwareConfig == True:
                            file_handle.write(f'    const int JSPinmap[] = {{{",".join(map(str, JSPinmap))}}};\n')
                            file_handle.write(f'    const int JSCenter[] = {{{",".join(map(str, JSPinCenter))}}};\n')
                            file_handle.write(f'    const int JSDeadband[] = {{{",".join(map(str, JSPinDeadbands))}}};\n')
                            file_handle.write(f'    const float JSScaling[] = {{{",".join(map(str, JSPinScaling))}}};\n')
                            file_handle.write(f'    const int JSPinAdresses[] = {{{",".join(map(str, allIntInPins[-JS:]))}}};\n')
                            file_handle.write(f'\n')

                
            ### Status LED
            if statusled:
                if debug == True:
                    print("Status LED:")
                SL = (len(statusled))
                if SL > 0:
                    if writeFirmwareConfig == True:
                        file_handle.write(f'//Status LED\n')
                        file_handle.write(f'#define STATUSLED\n')

                for pin in statusled:
                    StatusLed = pin.get('pin_id', 13)
                    StatusLedDled = pin.get('useDled', 0)
                    
                    if debug == True:
                        print(StatusLed)
                        print(StatusLedDled)

                    if writeFirmwareConfig == True:
                        file_handle.write(f'    const int StatusLed = {StatusLed};\n')
                        file_handle.write(f'    int StatLedErrDel[] = {{1000,10}};   //Blink Timing for Status LED Error (no connection)\n')
                        file_handle.write(f'    const int UseDLedStatusLed = {StatusLedDled};\n')
                        file_handle.write(f'\n')


            ### Digital LED
            if digitalLed:
                
                DLed = 0
                for pin in digitalLed:
                    if pin.get('pin_enabled', True):
                        DLed += 1
                        
                if DLed > 0:
                    if debug == True:
                        print("Digital LED:")
                    if writeFirmwareConfig == True:
                        file_handle.write(f'#define DIGITALLEDS\n')
                    
                    
                    DLedPin = []
                    DLedPinNames = []

                    DLedIds = []
                    DLedNames = []
                    DLedInits = []
                    DLedModes = []
                    DLed_on_values = []
                    DLed_off_values = []
                    DLed_Fades = []


                    Dled_Groupcounter = 0


                    for pin in digitalLed:
                        if pin.get('pin_enabled', True):
                            DLedPin = pin.get('pin_id', pin)
                            DLedStandardName = pin.get('Dled_name', f"dled-{pin}")
                            DLedStandardOnColor = pin.get('Dled_on_color', [255, 255, 255])
                            DLedStandardOffColor = pin.get('Dled_off_color', [0, 0, 0])
                            DLedStandardFade = pin.get('Dled_fade', 0)
                            DLedStandardMode = pin.get('Dled_mode', 0)
                            DLedStandardInit = pin.get('Dled_init_state', 0)
                            DledBrightness = pin.get('Dled_brightness', 70)
                            DledChainLength = 0

                            for dled in pin.get('Dleds', []):
                                if 'Dled_group' in dled:
                                    dled_group = dled['Dled_group']
                                    start_id = dled_group.get('Dled_group_start_id', 0)
                                    end_id = dled_group.get('Dled_group_end_id', 0)
                                    Group_name = dled_group.get('Dled_name', f'{DLedStandardName}_group_{Dled_Groupcounter}')
                                    Group_OnColor = dled_group.get('Dled_on_color', DLedStandardOnColor)
                                    Group_OffColor = dled_group.get('Dled_off_color', DLedStandardOffColor)
                                    Group_mode = dled_group.get('Dled_mode', DLedStandardMode)
                                    Group_fade = dled_group.get('Dled_fade', DLedStandardFade)
                                    Group_inits = dled_group.get('Dled_init_state', DLedStandardInit)

                                    Dled_Groupcounter += 1
                                    DLedIds.append(start_id)
                                    DLedNames.append(f"{Group_name}")
                                    DLedInits.append(Group_inits)
                                    DLedModes.append(Group_mode)
                                    DLed_on_values.append(Group_OnColor)
                                    DLed_off_values.append(Group_OffColor)
                                    DLed_Fades.append(Group_fade)

                                    if end_id > DledChainLength:
                                        DledChainLength = end_id
                                else:
                                    DLedIds.append(dled.get('Dled_id', 0))
                                    DLedNames.append(dled.get('Dled_name', f"{DLedStandardName}-{dled.get('Dled_id')}"))
                                    DLedInits.append(dled.get('Dled_init_state', DLedStandardInit))
                                    DLedModes.append(dled.get('Dled_mode', DLedStandardMode))
                                    DLed_on_values.append(dled.get('Dled_on_color', DLedStandardOnColor))
                                    DLed_off_values.append(dled.get('Dled_off_color', DLedStandardOffColor))
                                    DLed_Fades.append(dled.get('Dled_fade', DLedStandardFade))

                                    if DLedIds[-1] > DledChainLength:
                                        DledChainLength = DLedIds[-1]
                                    
                        
                        # Create a list of tuples containing all the data
                        dled_data = list(zip(DLedIds, DLedNames, DLedInits, DLedModes, DLed_on_values, DLed_off_values, DLed_Fades))
                        
                        # Sort the list of tuples by the first element (DLedIds)
                        dled_data.sort(key=lambda x: x[0])
                        
                        max_id = dled_data[-1][0]
                        complete_dled_data = []
                        existing_ids = {entry[0] for entry in dled_data}
                        
                        for i in range(max_id + 1):
                            if i in existing_ids:
                                complete_dled_data.append(dled_data.pop(0))
                            else:
                                complete_dled_data.append((i, f'{DLedStandardName}-{i}', 0, 0, [0, 0, 0], [0, 0, 0], 0))

                        # Unzip the sorted list of tuples back into individual lists
                        DLedIds, DLedNames, DLedInits, DLedModes, DLed_on_values, DLed_off_values, DLed_Fades = zip(*complete_dled_data)
                        
                        # Convert tuples back to lists
                        DLedIds = list(DLedIds)
                        DLedNames = list(DLedNames)
                        DLedInits = list(DLedInits)
                        DLedModes = list(DLedModes)
                        DLed_on_values = list(DLed_on_values)
                        DLed_off_values = list(DLed_off_values)
                        DLed_Fades = list(DLed_Fades)

                        Dled_Adresses = []
                        for i in range(len(DLedIds)):
                            Dled_Adresses.append(allBitOutPins[-1] + i + 1)
                        allBitOutPins.extend(Dled_Adresses)

                        if debug:
                            print(f"Dled Pin: {DLedPin}")
                            print(f"DLed Names: {DLedNames}")
                            print(f"DLed Ids: {DLedIds}")
                            print(f"DLed Inits: {DLedInits}")
                            print(f"DLed Modes: {DLedModes}")
                            print(f"DLed On Values: {DLed_on_values}")
                            print(f"DLed Off Values: {DLed_off_values}")
                            print(f"DLed Fades: {DLed_Fades}")
                            print(f"DLed Adresses: {Dled_Adresses}")
                            print(f"chain length: {DledChainLength}")
                        


                        if writeFirmwareConfig:
                            file_handle.write(f'    const int DLedPin = {DLedPin};\n')
                            file_handle.write(f'    const int DledBrightness = {DledBrightness};\n')
                            file_handle.write(f'    const int DLedInits[{DLedIds[-1]+1}] = {{{",".join(map(str, DLedInits))}}};\n')
                            file_handle.write(f'    const int DLedPinModes[{DLedIds[-1]+1}] = {{{",".join(map(str, DLedModes))}}};\n')
                            
                            DLed_on_values_str = ",".join(map(str, DLed_on_values)).replace('[', '{').replace(']', '}')
                            file_handle.write(f'    const int DLedPin_on_values[{DLedIds[-1]+1}][3] = {{{DLed_on_values_str}}};\n')
                            DLed_off_values_str = ",".join(map(str, DLed_off_values)).replace('[', '{').replace(']', '}')
                            file_handle.write(f'    const int DLedPin_off_values[{DLedIds[-1]+1}][3] = {{{DLed_off_values_str}}};\n')
                            
                            file_handle.write(f'    const int DLedPin_Fades[{DLedIds[-1]+1}] = {{{",".join(map(str, DLed_Fades))}}};\n')
                            file_handle.write(f'    const int DLedAdresses[{DLedIds[-1]+1}] = {{{",".join(map(str, Dled_Adresses))}}};\n')
                            file_handle.write(f'    const int DLedChainLength = {DledChainLength};\n')
                            file_handle.write(f'\n')

            
            ### Matrix Keyboard





            ### Dallas Thermistor

            ## communication Setup
            if writeFirmwareConfig == True:
                # [start_byte]
                #     [id_bytes]
                #     [binary_length][binary_payload]
                #     [int16_length][int16_payload]
                #     [uint16_length][uint16_payload]
                #     [int32_length][int32_payload]
                #     [uint32_length][uint32_payload]
                #     [float_length][float_payload]
                #     [char_length][char_payload]
                #     [string_length][string_payload]
                #     [checksum]
                # [end_byte]                file_handle.write('\n')
                file_handle.write('\n')
                file_handle.write("// Communication Variables\n //These variables are used to store the data that is sent and received over the serial interface.\n")
                file_handle.write(f'#define InBinaryLength {len(InBinaryPins)}\n')
                file_handle.write(f'bool InBinaryValues [{len(InBinaryPins) if len(InBinaryPins) > 0 else 1}] = {{0}};\n')

                file_handle.write(f'#define InInt16Length {len(InInt16Pins)}\n')
                file_handle.write(f' int InInt16Values [{len(InInt16Pins) if len(InInt16Pins) > 0 else 1}] = {{0}};\n')
                
                file_handle.write(f'#define InUint16Length {len(InUint16Pins)}\n')
                file_handle.write(f' unsigned int InUint16Values [{len(InUint16Pins) if len(InUint16Pins) > 0 else 1}] = {{0}};\n')

                file_handle.write(f'#define InInt32Length {len(InInt32Pins)}\n')
                file_handle.write(f' long InInt32Values [{len(InInt32Pins) if len(InInt32Pins) > 0 else 1}] = {{0}};\n')

                file_handle.write(f'#define InUint32Length {len(InUint32Pins)}\n')
                file_handle.write(f' unsigned long InUint32Values [{len(InUint32Pins) if len(InUint32Pins) > 0 else 1}] = {{0}};\n')

                file_handle.write(f'#define InFloatLength {len(InFloatPins)}\n')
                file_handle.write(f' float InFloatValues [{len(InFloatPins) if len(InFloatPins) > 0 else 1}] = {{0.0}};\n')

                file_handle.write(f'#define InCharLength {len(InCharPins)}\n')
                file_handle.write(f' char InCharValues [{len(InCharPins) if len(InCharPins) > 0 else 1}] = {{""}};\n')

                file_handle.write(f'#define InStringLength {len(InStringPins)}\n')
                file_handle.write(f' char InStringValues [{len(InStringPins) if len(InStringPins) > 0 else 1}] = {{""}};\n')
                file_handle.write('\n')

                file_handle.write(f'#define OutBinaryLength {len(OutBinaryPins)}\n')
                file_handle.write(f'bool OutBinaryValues [{len(OutBinaryPins) if len(OutBinaryPins) > 0 else 1}] = {{0}};\n')

                file_handle.write(f'#define OutInt16Length {len(OutInt16Pins)}\n')
                file_handle.write(f' int OutInt16Values [{len(OutInt16Pins) if len(OutInt16Pins) > 0 else 1}] = {{0}};\n')

                file_handle.write(f'#define OutUint16Length {len(OutUint16Pins)}\n')
                file_handle.write(f' unsigned int OutUint16Values [{len(OutUint16Pins) if len(OutUint16Pins) > 0 else 1}] = {{0}};\n')

                file_handle.write(f'#define OutInt32Length {len(OutInt32Pins)}\n')
                file_handle.write(f' long OutInt32Values [{len(OutInt32Pins) if len(OutInt32Pins) > 0 else 1}] = {{0}};\n')

                file_handle.write(f'#define OutUint32Length {len(OutUint32Pins)}\n')
                file_handle.write(f' unsigned long OutUint32Values [{len(OutUint32Pins) if len(OutUint32Pins) > 0 else 1}] = {{0}};\n')

                file_handle.write(f'#define OutFloatLength {len(OutFloatPins)}\n')
                file_handle.write(f' float OutFloatValues [{len(OutFloatPins) if len(OutFloatPins) > 0 else 1}] = {{0.0}};\n')

                file_handle.write(f'#define OutCharLength {len(OutCharPins)}\n')
                file_handle.write(f' char OutCharValues [{len(OutCharPins) if len(OutCharPins) > 0 else 1}] = {{""}};\n')

                file_handle.write(f'#define OutStringLength {len(OutStringPins)}\n')
                file_handle.write(f' char OutStringValues [{len(OutStringPins) if len(OutStringPins) > 0 else 1}] = {{""}};\n')
                file_handle.write('\n')

                #calculate buffer size InMessage
                InBufferSize = (len(InBinaryPins)*4) + (len(InBinaryPins)%8) + (len(InInt16Pins)*4) + (len(InUint16Pins)*2) + (len(InInt32Pins)*4) + (len(InUint32Pins)*4) + (len(InFloatPins)*4) + (len(InCharPins)*1) + (len(InStringPins)*1) + 1 
 
                file_handle.write(f'#define BufferInSize {} ;\n')

            config['mcu']['firmware_ID'] = firmwareID
            
            config['mcu']['InBinaryLength'] = len(InBinaryPins)
            config['mcu']['InBinaryPins'] = InBinaryPins
            config['mcu']['InInt16Length'] = len(InInt16Pins)
            config['mcu']['InInt16Pins'] = InInt16Pins
            config['mcu']['InUint16Length'] = len(InUint16Pins)
            config['mcu']['InUint16Pins'] = InUint16Pins
            config['mcu']['InInt32Length'] = len(InInt32Pins)
            config['mcu']['InInt32Pins'] = InInt32Pins
            config['mcu']['InUint32Length'] = len(InUint32Pins)
            config['mcu']['InUint32Pins'] = InUint32Pins
            config['mcu']['InFloatLength'] = len(InFloatPins)
            config['mcu']['InFloatPins'] = InFloatPins
            config['mcu']['InCharLength'] = len(InCharPins)
            config['mcu']['InCharPins'] = InCharPins
            config['mcu']['InStringLength'] = len(InStringPins)
            config['mcu']['InStringPins'] = InStringPins

            config['mcu']['OutBinaryLength'] = len(OutBinaryPins)
            config['mcu']['OutBinaryPins'] = OutBinaryPins
            config['mcu']['OutInt16Length'] = len(OutInt16Pins)
            config['mcu']['OutInt16Pins'] = OutInt16Pins
            config['mcu']['OutUint16Length'] = len(OutUint16Pins)
            config['mcu']['OutUint16Pins'] = OutUint16Pins
            config['mcu']['OutInt32Length'] = len(OutInt32Pins)
            config['mcu']['OutInt32Pins'] = OutInt32Pins
            config['mcu']['OutUint32Length'] = len(OutUint32Pins)
            config['mcu']['OutUint32Pins'] = OutUint32Pins
            config['mcu']['OutFloatLength'] = len(OutFloatPins)
            config['mcu']['OutFloatPins'] = OutFloatPins
            config['mcu']['OutCharLength'] = len(OutCharPins)
            config['mcu']['OutCharPins'] = OutCharPins
            config['mcu']['OutStringLength'] = len(OutStringPins)
            config['mcu']['OutStringPins'] = OutStringPins

        

    if file_handle:
        file_handle.close()

def save_config(file_path, configs):
    with open(file_path, 'w') as file:
        yaml.dump_all(configs, file, default_flow_style=False)

def compute_hash(config):
    hash_value = 0
    # Serialize the config object to a YAML string
    serialized_config = yaml.dump(config, default_flow_style=False)
    # Convert the YAML string to bytes
    config_bytes = serialized_config.encode('utf-8')
    # Compute the hash
    for byte in config_bytes:
        hash_value = (hash_value * 31 + byte) % (2**32)
    return hash_value

import struct
import serial

def calculate_checksum(data):
    return sum(data) % 256


########## Section for Serial Communication ##########

def print_hex(byte_sequence):
    #this function prints the message in hex format for debugging
    hex_values = [f'0x{byte:02X}' for byte in byte_sequence]

    # Join the hex values into a string
    hex_string = ', '.join(hex_values)
    print(f"Message: {hex_string}")


def pack_message(id_value, binary_states , int16_states , uint16_states, int32_states, uint32_states, float_states, char_states, string_states, debug = False):
    """
    This function packs the input data into a binary message format to send over a serial connection.
    It can be tested by calling it with debug=True, which will print the packed message to Terminal.
    The message starts with a Start byte 0xAA and ends with an cecksum Byte and an End byte 0xFF. 
    Each variable type is provided as a list of values. 
    For example:
    - Input pin states are given as a list of 0 or 1 states: [0, 1, 0, 1].
      First the number of Binary Pins is send as unsigned Int, then tall States are packed into bytes before being included in the message.
        -> [4] [0, 1, 0, 1] -> [0x0004] [0x05]
    - Analog pin states are given as a list of 16-bit integers: [-32768, 32767].
        First the number of Analog Pins is send as unsigned Int, then tall States are packed into bytes before being included in the message.
        -> [2] [-32768, 32767] -> [0x0002] [0x80 0x00 0x7F 0xFF]
    etc. 

    The function returns a binary message with the following structure:
    [start_byte]
        [id_bytes]
        [binary_length][binary_payload]
        [int16_length][int16_payload]
        [uint16_length][uint16_payload]
        [int32_length][int32_payload]
        [uint32_length][uint32_payload]
        [float_length][float_payload]
        [char_length][char_payload]
        [string_length][string_payload]
        [checksum]
    [end_byte]
    """

    if debug: #insert default values for testing
        if id_value is None: id_value = 123456789  # Unsigned Int32
        if binary_states is None: binary_states = [1, 0, 1, 1] # stored in bytes
        if int16_states is None: int16_states = [-32768, 32767]
        if uint16_states is None: uint16_states = [0, 65535]
        if int32_states is None: int32_states = [-2147483648, 2147483647]
        if uint32_states is None: uint32_states = [0, 4294967295]
        if float_states is None: float_states = [3.14, 2.718]
        if char_states is None: char_states = ['A', 'Z']
        if string_states is None: string_states = ["Hello", "World"]

    # Define start and end markers
    start_byte = 0xAA
    end_byte = 0xFF

    # Encode ID as 4 bytes (unsigned long)
    id_bytes = struct.pack('<L', id_value)

    # Encode binary states
    binary_length = len(binary_states)  # Length of binary states

    # Initialize an empty list to store the packed bytes
    binary_payload = []

    # Loop through the binary states in chunks of 8 bits
    for i in range(0, binary_length, 8):
        byte = 0
        for bit_index in range(8):
            if i + bit_index < binary_length:
                byte |= (binary_states[i + bit_index] << bit_index)
        binary_payload.append(byte)

    # Convert the list of bytes to a bytes object
    binary_payload = bytes(binary_payload)

    # Encode 16-bit integers
    int16_length = len(int16_states)
    int16_payload = b''.join(struct.pack('<h', val) for val in int16_states)

    # Encode 16-bit unsigned integers
    uint16_length = len(uint16_states)
    uint16_payload = b''.join(struct.pack('<H', val) for val in uint16_states)

    # Encode 32-bit integers
    int32_length = len(int32_states)
    int32_payload = b''.join(struct.pack('<l', val) for val in int32_states)

    # Encode 32-bit unsigned integers
    uint32_length = len(uint32_states)
    uint32_payload = b''.join(struct.pack('<L', val) for val in uint32_states)

    # Encode floats
    float_length = len(float_states)
    float_payload = b''.join(struct.pack('<f', val) for val in float_states)

    # Encode characters
    char_length = len(char_states)
    char_payload = b''.join(struct.pack('<c', val.encode('utf-8')) for val in char_states)

    # Encode strings
    string_payload = b''
    for s in string_states:
        string_payload += struct.pack('<H', len(s)) + s.encode('utf-8')
    string_length = len(string_states)

    # Build the payload
    payload = (
        id_bytes +
        struct.pack('<H', binary_length) + binary_payload +
        struct.pack('<H', int16_length) + int16_payload +
        struct.pack('<H', uint16_length) + uint16_payload +
        struct.pack('<H', int32_length) + int32_payload +
        struct.pack('<H', uint32_length) + uint32_payload +
        struct.pack('<H', float_length) + float_payload +
        struct.pack('<H', char_length) + char_payload +
        struct.pack('<H', string_length) + string_payload
    )

    # Calculate checksum
    checksum = calculate_checksum(payload)

    # Build the final message
    message = (
        bytes([start_byte]) +
        payload +
        bytes([checksum]) +
        bytes([end_byte])
    )

        
    if debug:
            print("packing Message:")
            print(f"Start ID: {int(start_byte)}")
            print(f"ID: {id_bytes} : {int.from_bytes(id_bytes, 'little')}")
            print(f"Binary Length: {binary_length}")
            binary_payload_str = ''.join(format(byte, '08b') for byte in binary_payload)
            print(f"Binary Payload: {binary_payload_str}")
            print(f"Int16 Length: {int16_length}")
            print(f"Int16 Payload: {[int.from_bytes(int16_payload[i:i+2], 'little', signed=True) for i in range(0, len(int16_payload), 2)]}")
            print(f"Uint16 Length: {uint16_length}")
            print(f"Uint16 Payload: {[int.from_bytes(uint16_payload[i:i+2], 'little') for i in range(0, len(uint16_payload), 2)]}")
            print(f"Int32 Length: {int32_length}")
            print(f"Int32 Payload: {[int.from_bytes(int32_payload[i:i+4], 'little', signed=True) for i in range(0, len(int32_payload), 4)]}")
            print(f"Uint32 Length: {uint32_length}")
            print(f"Uint32 Payload: {[int.from_bytes(uint32_payload[i:i+4], 'little') for i in range(0, len(uint32_payload), 4)]}")
            print(f"Float Length: {float_length}")
            print(f"Float Payload: {[struct.unpack('<f', float_payload[i:i+4])[0] for i in range(0, len(float_payload), 4)]}")
            print(f"Char Length: {char_length}")
            print(f"Char Payload: {[char_payload[i:i+1].decode('utf-8') for i in range(len(char_payload))]}")
            print(f"String Length: {string_length}")
            
            # Decode string payload correctly
            decoded_strings = []
            i = 0
            while i < len(string_payload):
                length = struct.unpack('<H', string_payload[i:i+2])[0]
                i += 2
                decoded_strings.append(string_payload[i:i+length].decode('utf-8'))
                i += length
            print(f"String Payload: {decoded_strings}")

            print(f"Checksum: {checksum}")
            print(f"End ID: {end_byte}")
            print(f"complete Message: {message}")

    return message

def unpack_message(message, id_value):
    start_byte = 0xAA
    end_byte = 0xFF


    # Convert the ID into 4 bytes (little-endian)
    id_bytes = struct.pack('<L', id_value)

    # Search for the pattern end_byte + start_byte + id_bytes
    pattern = bytes([start_byte]) + id_bytes
    try:
        for q in range(len(message) - len(pattern)):
            if message[q:q + len(pattern)] == pattern:
                # Extract the payload start posqtqon
                payload_start = q + len(pattern)

                    # [start_byte]
                    #     [id_bytes]
                    #     [binary_length][binary_payload]
                    #     [int16_length][int16_payload]
                    #     [uint16_length][uint16_payload]
                    #     [int32_length][int32_payload]
                    #     [uint32_length][uint32_payload]
                    #     [float_length][float_payload]
                    #     [char_length][char_payload]
                    #     [string_length][string_payload]
                    #     [checksum]
                    # [end_byte]

                index = payload_start
                # Extract binary states
                binary_length = message[index]
                index += 1
                binary_payload_length = (binary_length + 7) // 8  # Calculate the number of bytes needed
                binary_payload = message[index:index + binary_payload_length]
                index += binary_payload_length

                # Convert binary_payload to a list of bits
                bits = []
                for byte in binary_payload:
                    for bit_index in range(8):
                        bits.append((byte >> bit_index) & 1)
                        if len(bits) == binary_length:
                            break
                    if len(bits) == binary_length:
                        break
                binary_payload = bits




                # Extract 16-bit integers
                int16_length = int.from_bytes(message[index:index + 2], 'little')
                index += 2
                int16_payload = [int.from_bytes(message[i:i + 2], 'little', signed=True) for i in range(index, index + int16_length * 2, 2)]
                index += int16_length * 2

                # Extract 16-bit unsigned integers
                uint16_length = int.from_bytes(message[index:index + 2], 'little')
                index += 2
                uint16_payload = [int.from_bytes(message[i:i + 2], 'little') for i in range(index, index + uint16_length * 2, 2)]
                index += uint16_length * 2

                # Extract 32-bit integers
                int32_length = int.from_bytes(message[index:index + 2], 'little')
                index += 2
                int32_payload = [int.from_bytes(message[i:i + 4], 'little', signed=True) for i in range(index, index + int32_length * 4, 4)]
                index += int32_length * 4

                # Extract 32-bit unsigned integers
                uint32_length = int.from_bytes(message[index:index + 2], 'little')
                index += 2
                uint32_payload = [int.from_bytes(message[i:i + 4], 'little') for i in range(index, index + uint32_length * 4, 4)]
                index += uint32_length * 4

                # Extract floats
                float_length = int.from_bytes(message[index:index + 2], 'little')
                index += 2
                float_payload = [struct.unpack('<f', message[i:i + 4])[0] for i in range(index, index + float_length * 4, 4)]
                float_payload = [f"{val:.4f}" for val in float_payload]

                index += float_length * 4

                # Extract characters
                char_length = int.from_bytes(message[index:index + 2], 'little')
                index += 2
                char_payload = [message[i:i + 1].decode('utf-8') for i in range(index, index + char_length)]
                index += char_length

                # Extract the number of strings
                number_of_strings = int.from_bytes(message[index:index + 2], 'little')
                index += 2

                # Decode string payload correctly
                decoded_strings = []
                for _ in range(number_of_strings):
                    if len(message[index:index + 2]) < 2:
                        return None, 0  # Not enough data
                    length = struct.unpack('<H', message[index:index + 2])[0]
                    index += 2
                    if len(message[index:index + length]) < length:
                        return None, 0  # Not enough data
                    decoded_strings.append(message[index:index + length].decode('utf-8'))
                    index += length
                # # Extract strings
                # string_length = int.from_bytes(message[index:index + 2], 'little')
                # index += 2
                # string_payload = message[index:index + string_length]
                # index += string_length

                # # Decode string payload correctly
                # decoded_strings = []
                # i = 0
                # while i < len(string_payload):
                #     if len(string_payload[i:i + 2]) < 2:
                #         return None, 0  # Not enough data
                #     length = struct.unpack('<H', string_payload[i:i + 2])[0]
                #     i += 2
                #     if len(string_payload[i:i + length]) < length:
                #         return None, 0  # Not enough data
                #     decoded_strings.append(string_payload[i:i + length].decode('utf-8'))
                #     i += length
                # index += 1

                
                # Extract checksum from Byte before end_byte
                if message[index] == end_byte:
                    checksum = message[index - 1]
                else:
                    checksum = message[index]
                # calculate checksum of the payload
                calculatedPayload = message[q+1:index - 1]               
                #print(f"Calculated Payload: {calculatedPayload}") 
                if calculate_checksum(calculatedPayload) == checksum:
                    unpacked_message = {
                        'id': id_value,
                        'binary_payload': binary_payload,
                        'int16_payload': int16_payload,
                        'uint16_payload': uint16_payload,
                        'int32_payload': int32_payload,
                        'uint32_payload': uint32_payload,
                        'float_payload': float_payload,
                        'char_payload': char_payload,
                        'string_payload': decoded_strings,
                        'connection_state': 1
                    }
                    #print(unpacked_message)
                    return unpacked_message, index
                else:
                    if debug: print(f"Checksum Error: {calculatedPayload}, {checksum}")
                    return None, index
    except Exception as e:
        if debug: print(f"Error unpacking message: {e}")
        
    #print("Valid message not found")
    return None, 0



def communicate_with_arduinos(port, baudrate, timeout, firmware_ID, incoming_queue, outgoing_queue, stop_event):
    connection_state = 0  # 0 = not connected, 1 = connected, 2 = connection lost
    buffer = bytearray()
    bits_per_byte = 10  # 1 start bit, 8 data bits, 1 stop bit
    time_per_byte = bits_per_byte / baudrate
    sleep_time = time_per_byte * 20  # Sleep for 20 bytes worth of time


    while not stop_event.is_set():  #keep reconnecting if connection is lost
        try:
            if outgoing_queue.qsize() > 0:
                outgoing_data = outgoing_queue.get()
                message = pack_message(outgoing_data['id'], outgoing_data['binary_payload'], outgoing_data['int16_payload'], outgoing_data['uint16_payload'], outgoing_data['int32_payload'], outgoing_data['uint32_payload'], outgoing_data['float_payload'], outgoing_data['char_payload'], outgoing_data['string_payload'])
                #print(f"Message: {message}")
                print_hex(message)
            with serial.Serial(port, baudrate, timeout=timeout) as ser:
                while not stop_event.is_set():  #keep connection
                    if outgoing_queue.qsize() > 0:
                        outgoing_data = outgoing_queue.get()
                        message = pack_message(outgoing_data['id'], outgoing_data['binary_payload'], outgoing_data['int16_payload'], outgoing_data['uint16_payload'], outgoing_data['int32_payload'], outgoing_data['uint32_payload'], outgoing_data['float_payload'], outgoing_data['char_payload'], outgoing_data['string_payload'])
                        ser.write(message)
                        time.sleep(sleep_time)
                    if ser.in_waiting > 0:
                        print(ser.read(ser.in_waiting).decode('utf-8'))                    
                    '''
                    if ser.in_waiting > 0:
                        # Read data from serial port
                        data = ser.read(ser.in_waiting)
                        buffer.extend(data)
                        
                    try:
                        # Attempt to unpack a message
                        unpacked, index = unpack_message(buffer, firmware_ID)
                        ##print(f"Unpacked message: {unpacked}, buffer: {buffer}, index: {index}")

                        if unpacked is not None:
                            unpacked.setdefault('connection_state', connection_state)
                            ##print(f"Unpacked message: {unpacked}")
                            incoming_queue.put(unpacked)
                            #delete the unpacked message from the buffer
                            #print(f"Buffer before trimming: \n{buffer}")
                            buffer = buffer[index:]
                            #print(f"Buffer after trimming: \n{buffer}")
                            
                            if connection_state == 0 or connection_state == 2:
                                connection_state = 1
                                if debug: print(f"[{port}] Connected\n")
                            
                        else:
                            #print("No valid message unpacked yet, continuing to read data...")
                            # If no valid message is unpacked, remove everything up to the next start byte (0xAA)
                            start_index = buffer.find(bytes([0xAA]))
                            if start_index != -1:
                                buffer = buffer[start_index:]
                            else:
                                buffer.clear()

                    except Exception as e:
                        # If message is incomplete or invalid, wait for more data
                        #print(f"Error unpacking message: {e}")
                        pass
                        
                '''

        except serial.SerialException as e:
            if connection_state == 0:
                if debug: print(f"[{port}] Trying to connect to MCU")
            
            elif connection_state == 1:
                connection_state = 2  # Connection lost
                if debug: print(f"[{port}] Connection lost. Trying to reconnect...")
            
            elif connection_state == 2:
                if debug: print(f"[{port}] reconnecting to MCU.")
            time.sleep(0.5)  # Wait before trying to reconnect
        except Exception as e:
            if debug: print(f"[{port}] Error communicating with MCU: {e}")
            pass

config_path = "config.yaml"
configs = load_config(config_path)
process_config(configs,1)

#print(configs)
arduino_threads = []
arduino_ports = []
baudrates = []
timeouts = []
component_names = []
firmware_id = []
incoming_data = []
outgoing_data = []

# Thread-Stop-Event
stop_event = threading.Event()

# Global Variables for commnuication
for i in range(len(configs)):
    incoming_data.append(Queue())
    outgoing_data.append(Queue())

    arduino_ports.append(configs[i]['mcu']['dev'])
    component_names.append(configs[i]['mcu'].get('component_name', f'arducon.{i}'))
    print(configs[i])
    baudrates.append(configs[i]['mcu']['connection_baudrate'])
    timeouts.append(configs[i]['mcu']['connection_baudrate'])
    firmware_id.append(configs[i]['mcu']['firmware_ID'])


    thread = threading.Thread(
        target = communicate_with_arduinos,
        args = (arduino_ports[i], baudrates[i], timeouts[i], firmware_id[i], incoming_data[i], outgoing_data[i], stop_event),
        daemon = True
    )
    arduino_threads.append(thread)
    thread.start()

print(threading.active_count())


# Hauptprogramm
try:
    print("Drücke STRG+C zum Beenden...")
    while True:
        for i in range(len(configs)):
            data_to_send = {'id':firmware_id[i], 
                'binary_payload':[1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1],
                'int16_payload':[-32768, 32767], 
                'uint16_payload':[0, 65535], 
                'int32_payload':[-2147483648, 2147483647], 
                'uint32_payload':[0, 4294967295], 
                'float_payload':[3.14, 2.81312], 
                'char_payload':['A', 'Z'], 
                'string_payload':["Hello", "World"]}
            if outgoing_data[i].empty():
                outgoing_data[i].put(data_to_send)

            #print(f"received {incoming_data[i].get()}")
            #print("reading")

        time.sleep(0.001)

except KeyboardInterrupt:
    print("\nBeenden des Programms...")

# Stoppe alle Threads
stop_event.set()
for thread in arduino_threads:
    thread.join()

print("Programm beendet.")
