from enum import StrEnum

class EnvParams(StrEnum):
    ARDUINO_CONNECTOR_ENABLE_LOG = "ARDUINO_CONNECTOR_ENABLE_LOG"
    ARDUINO_CONNECTOR_LOG_FORMAT = "ARDUINO_CONNECTOR_LOG_FORMAT"
    ARDUINO_CONNECTOR_LOG_LEVEL = "ARDUINO_CONNECTOR_LOG_LEVEL"
    ARDUINO_CONNECTOR_LOG_FILE_PATH = "ARDUINO_CONNECTOR_LOG_FILE_PATH"
    ARDUINO_CONNECTOR_LOGFILE_NAME = "ARDUINO_CONNECTOR_LOGFILE_NAME"
    ARDUINO_CONNECTOR_ENABLE_REMOTE_DEBUG = "ARDUINO_CONNECTOR_ENABLE_REMOTE_DEBUG"
    ARDUINO_CONNECTOR_REMOTE_DEBUG_BIND_ADDRESS = "ARDUINO_CONNECTOR_REMOTE_DEBUG_BIND_ADDRESS"
    ARDUINO_CONNECTOR_REMOTE_DEBUG_PORT = "ARDUINO_CONNECTOR_REMOTE_DEBUG_PORT"
    ARDUINO_CONNECTOR_WAIT_ON_REMOTE_DEBUG = "ARDUINO_CONNECTOR_WAIT_ON_REMOTE_DEBUG"


