# Defaults
DEFAULT_PROFILE_NAME = 'default_profile.yaml'
DEFAULT_LINUXCNC_PROFILE_INI_HEADER = 'ARDUINO_CONNECTOR'
DEFAULT_LINUXCNC_PROFILE_INI_YAML_PATH_KEY = 'YAML_PROFILE_PATH'
DEFAULT_LINUXCNC_PROFILE_INI_REMOTE_DEBUG_KEY = 'REMOTE_DEBUG'
DEFAULT_LINUXCNC_PROFILE_INI_WAIT_ON_REMOTE_DEBUG_CONNECT_KEY = 'WAIT_ON_REMOTE_DEBUG_CONNECT'
DEFAULT_LINUXCNC_PROFILE_INI_REMOTE_DEBUG_PORT_KEY = 'REMOTE_DEBUG_PORT'
DEFAULT_LINUXCNC_PROFILE_INI_LOG_PATH_KEY = 'LOG_PATH'
DEFAULT_LINUXCNC_PROFILE_INI_LOG_LEVEL_KEY = 'LOG_LEVEL'
DEFAULT_LINUXCNC_PROFILE_INI_REMOTE_DEBUG_BIND_ADDRESS_KEY = 'REMOTE_DEBUG_BIND_ADDRESS'
# The following will override any other settings such as from the linuxcnc profile.
# Use these overrides for debugging purposes, such as some mysterious startup crash.
DEFAULT_LOGGING_ENABLED = True
DEFAULT_LOGGING_FORMAT = '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
DEFAULT_LOG_TO_CONSOLE = True

DEFAULT_LOG_FILE_PATH = '/tmp/arduino_connector/logs'
DEFAULT_LOG_LEVEL = 'DEBUG'

DEFAULT_REMOTE_DEBUG_ENABLED = False
DEFAULT_REMOTE_DEBUG_PORT = 5678
DEFAULT_REMOTE_DEBUG_BIND_ADDRESS = '0.0.0.0'
DEFAULT_REMOTE_DEBUG_WAIT_ON_CONNECT = False

# API Configuration
DEFAULT_API_ENABLED = True
DEFAULT_API_PORT = 8765
DEFAULT_API_BIND_ADDRESS = '0.0.0.0'
